### ISSUE TITLE
Lots of things are not Copy/Clone where they could be (maybe?)

### ISSUE THREAD

**Issue by Restioson** [rust-osdev/multiboot2-elf64#44] opened 2018-05-11 17:53 UTC
Apparently, ModulesIter and co are not Copy or Clone. Is there a reason for this? So far I've just hacked around this [here](https://github.com/Restioson/multiboot2-elf64/commit/83bb085ef0d58ea17bf9c2756aaca95964ec139c).

**Comment by 4e554c4c** [comment] 2018-05-12 03:41
Why should they be? I can think of several reasons they should not be.

**Comment by Restioson** [comment] 2018-05-12 07:03
Well, I thought that since ModuleTag is literally just comprised of fields that are Copy, it could be copy too, and by extension ModulesIter. What reasons?

**Comment by phil-opp** [comment] 2018-05-12 14:11
You should not be able to copy an iterator by accident, because you then get the same items multiple times. Imagine the following:

```rust
let skip_one_element = |iter| { iter.next() };

let iter = module_iter(…);
skip_one_element(iter);
let module = iter.next();
```

This wouldn't work as intended, because `iter` is silently copied (it should be `&mut iter` instead).

Implementing `Clone` would be fine with me, because then it stays explicit.

**Comment by Restioson** [comment] 2018-05-12 14:12
Fair, I guess.

**Comment by robert-w-gries** [comment] 2020-01-16 20:11
Looks like this issue was resolved? Closing for now.

**Closed by robert-w-gries** 2020-01-16 20:11 UTC
